name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - name: install mpi
        run: sudo apt-get update
      - run: sudo apt-get install -y mpich
      - name: download miniconda manually
        run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - name: run install
        run: bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
      - name: run path export
        run: export PATH=~/miniconda/bin:${PATH}
      - run: julia --color=yes --project -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end'
        shell: bash
        env:
          PYTHON: '~/miniconda/bin/python3'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
