name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.5]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: install mpi
        run: sudo apt-get install -y openmpi-bin libopenmpi-dev
      - uses: julia-actions/julia-buildpkg@master
      - run: ls /home/runner/.julia/conda/3/bin
      - run: export PATH=/home/runner/.julia/conda/3/bin/:/home/runner/.julia/conda/3/condabin:$PATH
      - uses: julia-actions/julia-runtest@master
        env:
          PYTHON: /home/runner/.julia/conda/3/bin/python3
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info